services:
  clickhouse:
    container_name: clickhouse
    image: clickhouse/clickhouse-server:23.9
    restart: always
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    healthcheck:
      test: ["CMD", "clickhouse-client", "-q", "SELECT 1"]
      interval: 30s
      timeout: 5s
      retries: 3
    volumes:
      - "./data:/var/lib/clickhouse/"
  backend:
    container_name: backend
    build: .
    command: python app/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"

volumes:
  clickhouse:
    name: test-clickhouse

networks:
  default:
    name: test-net
